name = "arknights-toolbox-json-storage"
main = "src/index.ts"
compatibility_date = "2024-01-29"

routes = [{ pattern = "json.arkntools.app", custom_domain = true }]

[triggers]
crons = ["0 0 1 * *"]

[vars]
ALLOW_ORIGIN = "https://arkn.lolicon.app,https://arknbak.lolicon.app"

[[d1_databases]]
binding = "DB"
database_name = "arknights-toolbox-json-storage"
database_id = "7b303c7b-6507-4b94-af6b-f26384f44f0f"
